version: '3'

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.83.0/24

services:
  db:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
